config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    get "users/new"
    root "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login",   to: "sessions#new"
    post "/login",   to: "sessions#create"
    delete "/logout",  to: "sessions#destroy"
    resources :users
    resources :microposts, only: [:create, :destroy]
    resources :relationships, only: [:index, :create, :destroy]
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    return unless logged_in?
    @micropost  = current_user.microposts.build
    @feed_items = Micropost.status_feed(current_user).created_at_desc
                           .paginate page:
                           params[:page], per_page: Settings.per_page
  end

  def help; end

  def about; end

  def contact; end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide :title, t(".description") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %> </title>
  </head>
  <body>
    <h1><%= t ".description" %></h1>
    <%= t ".content_html" %>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide :title, t(".description") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %> </title>
  </head>
  <body>
    <h1><%= t ".description" %></h1>
    <%= t ".content_html" %>
  </body>
</html>

app/views/static_pages/help.html.erb
<% provide :title, t(".description") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %> </title>
  </head>
  <body>
    <h1><%= t ".description" %></h1>
    <%= t ".content_html" %>
  </body>
</html>

app/views/static_pages/home.html.erb
<% provide :title, t(".description") %>
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render "shared/user_info" %>
      </section>
      <section class="stats">
        <%= render "shared/stats" %>
      </section>
      <section class="micropost_form">
        <%= render "shared/micropost_form" %>
      </section>
    </aside>
    <div class="col-md-8">
      <%= t ".feed_html" %>
      <%= render "shared/feed" %>
    </div>
  </div>
<% else %>
<div class="center jumbotron">
  <h1><%= t ".description" %></h1>
  <%= t ".content_html" %>
  <%= link_to t(".sign_up"), signup_path, class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("rails.png", alt: "Rails logo"),
'http://rubyonrails.org/' %>
<% end %>